GET http://localhost:4004/v2/odata/EMPLOYEE

###

DELETE http://localhost:4004/v2/odata/EMPLOYEE(4)

###
POST http://localhost:4004/v2/odata/EMPLOYEE
Content-Type: application/json

{
    "EMP_AGE": "30",
        "EMP_COUNTRY": "Bihar",
        "EMP_ID": 5,
        "EMP_NAME": "Sitaram",
        "EMP_SALARY": "28000",
        "EMP_STATUS": true,
        "PASSWORD": "s12345",
        "TILE_VISIBLITY": []
}


###
POST http://localhost:4004/odata/loginEmployee
Content-Type: application/json

{
    "EMP_NAME":"Bhavesh",
    "PASSWORD":"b12345"
}

###
GET http://localhost:4004/v2/odata/ADMIN

###

POST http://localhost:4004/odata/loginAdmin
Content-Type: application/json

{
    "ADMIN_NAME":"Nainesh",
    "PASSWORD":"n12345"
}

###
POST http://localhost:4004/v2/odata/ADMIN
Content-Type: application/json

{
    "ADMIN_ID":3,
    "ADMIN_NAME":"Nainesh",
    "PASSWORD":"n12345"
}